services:
  telemt:
    image: raylabpro/telemt
    
    ports:
      - 443:443
      - 9090:9090
      - 9091:9091
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    ulimits:
      nofile: 65536
    # network_mode: "host"
    
    environment:
      - SECRET=93b8f1d3c5e2a4b67890def123456789
      - PORT=443
      - TLS_DOMAIN=github.com
      - MODE=tls
    # user: "0:0"
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
